[package]
name = "i3_battery"
version = "0.1.0"
authors = ["Kyle Laker <kyle@laker.email>"]
edition = "2018"

[dependencies]
nix = "0.10.0"
libnotify = "1.0.3"

[dependencies.gtk]
version = "0.3.0"
features = ["v3_10"]
